module.exports = {
  apps: [
    {
      name: 'nexus-web',
      script: 'npx',
      args: 'next start -p 4400',
      cwd: '/home/openclaw/projects/1ai-tracker',
      env: {
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/nexus',
        REDIS_URL: 'redis://localhost:6379',
        NODE_ENV: 'production',
        PORT: '4400',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      exp_backoff_restart_delay: 100,
      max_restarts: 100,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/tmp/nexus-web-error.log',
      out_file: '/tmp/nexus-web-out.log',
      merge_logs: true,
    },
    {
      name: 'nexus-ws',
      script: 'npx',
      args: 'tsx server.ts',
      cwd: '/home/openclaw/projects/1ai-tracker/ws-server',
      env: {
        REDIS_URL: 'redis://localhost:6379',
        WS_PORT: '4401',
        NEXUS_API_KEYS: process.env.NEXUS_API_KEYS || '',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      max_restarts: 100,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/tmp/nexus-ws-error.log',
      out_file: '/tmp/nexus-ws-out.log',
      merge_logs: true,
    },
    {
      name: 'nexus-mcp',
      script: 'npx',
      args: 'tsx index.ts',
      cwd: '/home/openclaw/projects/1ai-tracker/mcp-server',
      env: {
        MCP_PORT: '4402',
        NEXUS_API_URL: 'http://localhost:4400',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      exp_backoff_restart_delay: 100,
      max_restarts: 100,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/tmp/nexus-mcp-error.log',
      out_file: '/tmp/nexus-mcp-out.log',
      merge_logs: true,
    },
    {
      name: 'nexus-indexer',
      script: 'npx',
      args: 'tsx main.ts',
      cwd: '/home/openclaw/projects/1ai-tracker/indexer',
      env: {
        DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/nexus',
        REDIS_URL: 'redis://localhost:6379',
        HEALTH_PORT: '4409',
        LOG_LEVEL: 'info',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      max_restarts: 100,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/tmp/nexus-indexer-error.log',
      out_file: '/tmp/nexus-indexer-out.log',
      merge_logs: true,
    },
  ],
};
